CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE cliente (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    senha character varying(100) NOT NULL,
    cpf_cnpj character varying(14) NOT NULL,
    obs character varying(500),
    razao character varying(500),
    datanasc date,
    sexo integer NOT NULL,
    numero integer NOT NULL,
    rua character varying(500) NOT NULL,
    cidade character varying(500) NOT NULL,
    cep text NOT NULL,
    bairro character varying(500) NOT NULL,
    estado character varying(500) NOT NULL,
    pais character varying(500) NOT NULL,
    complemento character varying(500) NOT NULL,
    tipocliente integer NOT NULL,
    situacao integer NOT NULL,
    CONSTRAINT "PK_cliente" PRIMARY KEY (id)
);

CREATE TABLE oficina (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(100) NOT NULL,
    cnpj text NOT NULL,
    email character varying(100) NOT NULL,
    numero integer NOT NULL,
    rua character varying(200) NOT NULL,
    cidade character varying(100) NOT NULL,
    cep integer NOT NULL,
    bairro character varying(100) NOT NULL,
    estado character varying(50) NOT NULL,
    pais character varying(50) NOT NULL,
    complemento character varying(200),
    senha text NOT NULL,
    situacao integer NOT NULL,
    CONSTRAINT "PK_oficina" PRIMARY KEY (id)
);

CREATE TABLE compartilhamento_cliente (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    id_cliente integer NOT NULL,
    codigo_hash character varying(128) NOT NULL,
    dados_permitidos text NOT NULL,
    expira_em timestamp with time zone NOT NULL,
    usado_em timestamp with time zone,
    ativo boolean NOT NULL,
    CONSTRAINT "PK_compartilhamento_cliente" PRIMARY KEY (id),
    CONSTRAINT "FK_compartilhamento_cliente_cliente_id_cliente" FOREIGN KEY (id_cliente) REFERENCES cliente (id) ON DELETE CASCADE
);

CREATE TABLE veiculo (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(100) NOT NULL,
    tipo character varying(50) NOT NULL,
    placa character varying(8) NOT NULL,
    chassi character varying(17) NOT NULL,
    ano integer NOT NULL,
    quilometragem integer NOT NULL,
    combustivel character varying(30) NOT NULL,
    seguro character varying(100),
    cor text NOT NULL,
    status integer NOT NULL,
    id_cliente integer NOT NULL,
    CONSTRAINT "PK_veiculo" PRIMARY KEY (id),
    CONSTRAINT "AK_veiculo_id_id_cliente" UNIQUE (id, id_cliente),
    CONSTRAINT "FK_veiculo_cliente_id_cliente" FOREIGN KEY (id_cliente) REFERENCES cliente (id) ON DELETE CASCADE
);

CREATE TABLE cliente_oficina (
    id_oficina integer NOT NULL,
    id_cliente integer NOT NULL,
    ativo boolean NOT NULL,
    dados_permitidos text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_cliente_oficina" PRIMARY KEY (id_oficina, id_cliente),
    CONSTRAINT "FK_cliente_oficina_cliente_id_cliente" FOREIGN KEY (id_cliente) REFERENCES cliente (id) ON DELETE CASCADE,
    CONSTRAINT "FK_cliente_oficina_oficina_id_oficina" FOREIGN KEY (id_oficina) REFERENCES oficina (id) ON DELETE CASCADE
);

CREATE TABLE compartilhamento_cliente_tentativa (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    id_oficina integer NOT NULL,
    codigo_hash character varying(128) NOT NULL,
    ip_address character varying(64),
    sucesso boolean NOT NULL,
    motivo character varying(64) NOT NULL,
    tentado_em timestamp with time zone NOT NULL,
    CONSTRAINT "PK_compartilhamento_cliente_tentativa" PRIMARY KEY (id),
    CONSTRAINT "FK_compartilhamento_cliente_tentativa_oficina_id_oficina" FOREIGN KEY (id_oficina) REFERENCES oficina (id) ON DELETE CASCADE
);

CREATE TABLE funcionario (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(100) NOT NULL,
    cpf character varying(12) NOT NULL,
    cargo character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    senha text NOT NULL,
    role character varying(30) NOT NULL DEFAULT 'Funcionario',
    situacao integer NOT NULL,
    id_oficina integer,
    CONSTRAINT "PK_funcionario" PRIMARY KEY (id),
    CONSTRAINT "FK_funcionario_oficina_id_oficina" FOREIGN KEY (id_oficina) REFERENCES oficina (id) ON DELETE RESTRICT
);

CREATE TABLE servico (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(100) NOT NULL,
    descricao text NOT NULL,
    valor numeric(18,2) NOT NULL,
    garantia date NOT NULL,
    id_oficina integer,
    CONSTRAINT "PK_servico" PRIMARY KEY (id),
    CONSTRAINT "FK_servico_oficina_id_oficina" FOREIGN KEY (id_oficina) REFERENCES oficina (id) ON DELETE RESTRICT
);

CREATE TABLE marca (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(100) NOT NULL,
    "desc" character varying(500),
    tipomarca character varying(50) NOT NULL,
    CONSTRAINT "PK_marca" PRIMARY KEY (id)
);

CREATE TABLE veiculo_imagem (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    id_veiculo integer NOT NULL,
    url character varying(300) NOT NULL,
    nome_arquivo character varying(150) NOT NULL,
    nome_original character varying(255) NOT NULL,
    content_type character varying(100) NOT NULL,
    tamanho_bytes bigint NOT NULL,
    criado_em timestamp with time zone NOT NULL,
    CONSTRAINT "PK_veiculo_imagem" PRIMARY KEY (id),
    CONSTRAINT "FK_veiculo_imagem_veiculo_id_veiculo" FOREIGN KEY (id_veiculo) REFERENCES veiculo (id) ON DELETE CASCADE
);

CREATE TABLE pedido (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    id_cliente integer NOT NULL,
    id_funcionario integer NOT NULL,
    id_oficina integer NOT NULL,
    id_veiculo integer NOT NULL,
    "valorTotal" numeric(18,2) NOT NULL,
    "descontoReais" numeric(18,2) NOT NULL,
    "descontoPorcentagem" numeric(5,2) NOT NULL,
    "descontoTotalReais" numeric(18,2) NOT NULL,
    "descontoServicoPorcentagem" numeric(5,2) NOT NULL,
    "descontoServicoReais" numeric(18,2) NOT NULL,
    "descontoPecaPorcentagem" numeric(5,2) NOT NULL,
    "descontoPecaReais" numeric(18,2) NOT NULL,
    observacao character varying(500),
    "dataInicio" date NOT NULL,
    "dataFim" date NOT NULL,
    CONSTRAINT "PK_pedido" PRIMARY KEY (id),
    CONSTRAINT "FK_pedido_cliente_id_cliente" FOREIGN KEY (id_cliente) REFERENCES cliente (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_pedido_cliente_oficina_id_oficina_id_cliente" FOREIGN KEY (id_oficina, id_cliente) REFERENCES cliente_oficina (id_oficina, id_cliente) ON DELETE RESTRICT,
    CONSTRAINT "FK_pedido_funcionario_id_funcionario" FOREIGN KEY (id_funcionario) REFERENCES funcionario (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_pedido_oficina_id_oficina" FOREIGN KEY (id_oficina) REFERENCES oficina (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_pedido_veiculo_id_veiculo_id_cliente" FOREIGN KEY (id_veiculo, id_cliente) REFERENCES veiculo (id, id_cliente) ON DELETE RESTRICT
);

CREATE TABLE telefone (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    numero character varying(9) NOT NULL,
    ddd integer NOT NULL,
    clienteid integer NOT NULL,
    "FuncionarioId" integer,
    "OficinaId" integer,
    CONSTRAINT "PK_telefone" PRIMARY KEY (id),
    CONSTRAINT "FK_telefone_cliente_clienteid" FOREIGN KEY (clienteid) REFERENCES cliente (id) ON DELETE CASCADE,
    CONSTRAINT "FK_telefone_funcionario_FuncionarioId" FOREIGN KEY ("FuncionarioId") REFERENCES funcionario (id),
    CONSTRAINT "FK_telefone_oficina_OficinaId" FOREIGN KEY ("OficinaId") REFERENCES oficina (id)
);

CREATE TABLE funcionario_servico (
    "idFuncionario" integer NOT NULL,
    "idServico" integer NOT NULL,
    tempodec text,
    CONSTRAINT "PK_funcionario_servico" PRIMARY KEY ("idFuncionario", "idServico"),
    CONSTRAINT "FK_funcionario_servico_funcionario_idFuncionario" FOREIGN KEY ("idFuncionario") REFERENCES funcionario (id) ON DELETE CASCADE,
    CONSTRAINT "FK_funcionario_servico_servico_idServico" FOREIGN KEY ("idServico") REFERENCES servico (id) ON DELETE CASCADE
);

CREATE TABLE registro_servico (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    id_veiculo integer NOT NULL,
    id_servico integer,
    data_servico timestamp with time zone NOT NULL,
    descricao text,
    quilometragem integer NOT NULL,
    responsavel text,
    CONSTRAINT "PK_registro_servico" PRIMARY KEY (id),
    CONSTRAINT "FK_registro_servico_servico_id_servico" FOREIGN KEY (id_servico) REFERENCES servico (id) ON DELETE SET NULL,
    CONSTRAINT "FK_registro_servico_veiculo_id_veiculo" FOREIGN KEY (id_veiculo) REFERENCES veiculo (id) ON DELETE RESTRICT
);

CREATE TABLE peca (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nome character varying(100) NOT NULL,
    tipo character varying(100) NOT NULL,
    descricao character varying(500),
    valor numeric(18,2) NOT NULL,
    quantidade integer NOT NULL,
    garantia date NOT NULL,
    unidade integer NOT NULL,
    idmarca integer NOT NULL,
    "dataAquisicao" date NOT NULL,
    fornecedor character varying(100) NOT NULL,
    id_oficina integer,
    CONSTRAINT "PK_peca" PRIMARY KEY (id),
    CONSTRAINT "FK_peca_marca_idmarca" FOREIGN KEY (idmarca) REFERENCES marca (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_peca_oficina_id_oficina" FOREIGN KEY (id_oficina) REFERENCES oficina (id) ON DELETE RESTRICT
);

CREATE TABLE pedido_servico (
    "idPedido" integer NOT NULL,
    "idServico" integer NOT NULL,
    "quantVezes" integer NOT NULL,
    valor_unitario numeric(18,2) NOT NULL,
    CONSTRAINT "PK_pedido_servico" PRIMARY KEY ("idPedido", "idServico"),
    CONSTRAINT "FK_pedido_servico_pedido_idPedido" FOREIGN KEY ("idPedido") REFERENCES pedido (id) ON DELETE CASCADE,
    CONSTRAINT "FK_pedido_servico_servico_idServico" FOREIGN KEY ("idServico") REFERENCES servico (id) ON DELETE RESTRICT
);

CREATE TABLE peca_substituida (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    id_registro_servico integer NOT NULL,
    nome text,
    quantidade integer NOT NULL,
    observacao text,
    CONSTRAINT "PK_peca_substituida" PRIMARY KEY (id),
    CONSTRAINT "FK_peca_substituida_registro_servico_id_registro_servico" FOREIGN KEY (id_registro_servico) REFERENCES registro_servico (id) ON DELETE CASCADE
);

CREATE TABLE pedido_peca (
    idpedido integer NOT NULL,
    idpeca integer NOT NULL,
    quantidade integer NOT NULL,
    valor_unitario numeric(18,2) NOT NULL,
    datainstalacao date NOT NULL,
    estado text,
    observacao text,
    CONSTRAINT "PK_pedido_peca" PRIMARY KEY (idpedido, idpeca),
    CONSTRAINT "FK_pedido_peca_peca_idpeca" FOREIGN KEY (idpeca) REFERENCES peca (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_pedido_peca_pedido_idpedido" FOREIGN KEY (idpedido) REFERENCES pedido (id) ON DELETE CASCADE
);

CREATE INDEX "IX_cliente_oficina_id_cliente" ON cliente_oficina (id_cliente);

CREATE INDEX "IX_cliente_oficina_oficina_ativo_cliente" ON cliente_oficina (id_oficina, ativo, id_cliente);

CREATE UNIQUE INDEX "IX_compartilhamento_cliente_codigo_hash" ON compartilhamento_cliente (codigo_hash) WHERE ativo AND usado_em IS NULL;

CREATE INDEX "IX_compartilhamento_cliente_id_cliente" ON compartilhamento_cliente (id_cliente);

CREATE INDEX "IX_compartilhamento_cliente_tentativa_id_oficina_ip_address_te~" ON compartilhamento_cliente_tentativa (id_oficina, ip_address, tentado_em);

CREATE UNIQUE INDEX "IX_funcionario_cpf" ON funcionario (cpf);

CREATE UNIQUE INDEX "IX_funcionario_email" ON funcionario (email);

CREATE INDEX "IX_funcionario_id_oficina_nome" ON funcionario (id_oficina, nome);

CREATE INDEX "IX_funcionario_servico_idServico" ON funcionario_servico ("idServico");

CREATE UNIQUE INDEX "IX_oficina_cnpj" ON oficina (cnpj);

CREATE UNIQUE INDEX "IX_oficina_email" ON oficina (email);

CREATE INDEX "IX_peca_id_oficina_nome" ON peca (id_oficina, nome);

CREATE INDEX "IX_peca_idmarca" ON peca (idmarca);

CREATE INDEX "IX_peca_substituida_id_registro_servico" ON peca_substituida (id_registro_servico);

CREATE INDEX "IX_pedido_id_cliente" ON pedido (id_cliente);

CREATE INDEX "IX_pedido_id_funcionario" ON pedido (id_funcionario);

CREATE INDEX "IX_pedido_id_oficina_id_cliente" ON pedido (id_oficina, id_cliente);

CREATE INDEX "IX_pedido_id_veiculo_dataInicio" ON pedido (id_veiculo, "dataInicio" DESC);

CREATE INDEX "IX_pedido_id_veiculo_id_cliente" ON pedido (id_veiculo, id_cliente);

CREATE INDEX "IX_pedido_peca_idpeca" ON pedido_peca (idpeca);

CREATE INDEX "IX_pedido_servico_idServico" ON pedido_servico ("idServico");

CREATE INDEX "IX_registro_servico_id_servico" ON registro_servico (id_servico);

CREATE INDEX "IX_registro_servico_veiculo_data" ON registro_servico (id_veiculo, data_servico DESC);

CREATE INDEX "IX_servico_id_oficina_nome" ON servico (id_oficina, nome);

CREATE INDEX "IX_telefone_clienteid" ON telefone (clienteid);

CREATE INDEX "IX_telefone_FuncionarioId" ON telefone ("FuncionarioId");

CREATE INDEX "IX_telefone_OficinaId" ON telefone ("OficinaId");

CREATE INDEX "IX_veiculo_id_cliente" ON veiculo (id_cliente);

CREATE UNIQUE INDEX "IX_veiculo_imagem_nome_arquivo" ON veiculo_imagem (nome_arquivo);

CREATE INDEX "IX_veiculo_imagem_veiculo_criado_em" ON veiculo_imagem (id_veiculo, criado_em);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260527163546_AtualizandoOBanco', '9.0.9');

CREATE TABLE IF NOT EXISTS cliente_oficina (
    id_oficina integer NOT NULL,
    id_cliente integer NOT NULL,
    ativo boolean NOT NULL DEFAULT TRUE,
    dados_permitidos text NOT NULL DEFAULT '["Nome","Email","Cpf_Cnpj","Telefones","Veiculos"]',
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE cliente_oficina
    ADD COLUMN IF NOT EXISTS ativo boolean NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS dados_permitidos text NOT NULL DEFAULT '["Nome","Email","Cpf_Cnpj","Telefones","Veiculos"]',
    ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT now();

DO $migration$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'PK_cliente_oficina'
    ) THEN
        ALTER TABLE cliente_oficina
            ADD CONSTRAINT "PK_cliente_oficina" PRIMARY KEY (id_oficina, id_cliente);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_cliente_oficina_cliente_id_cliente'
    ) THEN
        ALTER TABLE cliente_oficina
            ADD CONSTRAINT "FK_cliente_oficina_cliente_id_cliente"
            FOREIGN KEY (id_cliente) REFERENCES cliente (id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_cliente_oficina_oficina_id_oficina'
    ) THEN
        ALTER TABLE cliente_oficina
            ADD CONSTRAINT "FK_cliente_oficina_oficina_id_oficina"
            FOREIGN KEY (id_oficina) REFERENCES oficina (id) ON DELETE CASCADE;
    END IF;
END $migration$;

INSERT INTO cliente_oficina (id_oficina, id_cliente, ativo, dados_permitidos, created_at, updated_at)
SELECT DISTINCT
    p.id_oficina,
    p.id_cliente,
    TRUE,
    '["Nome","Email","Cpf_Cnpj","Telefones","Veiculos"]',
    now(),
    now()
FROM pedido p
INNER JOIN oficina o ON o.id = p.id_oficina
INNER JOIN cliente c ON c.id = p.id_cliente
ON CONFLICT (id_oficina, id_cliente) DO UPDATE
SET ativo = TRUE,
    updated_at = excluded.updated_at;

DO $migration$
BEGIN
    IF to_regclass('public.oficina_cliente') IS NOT NULL THEN
        EXECUTE '
            INSERT INTO cliente_oficina (id_oficina, id_cliente, ativo, dados_permitidos, created_at, updated_at)
            SELECT DISTINCT
                oc.id_oficina,
                oc.id_cliente,
                TRUE,
                ''["Nome","Email","Cpf_Cnpj","Telefones","Veiculos"]'',
                now(),
                now()
            FROM oficina_cliente oc
            INNER JOIN oficina o ON o.id = oc.id_oficina
            INNER JOIN cliente c ON c.id = oc.id_cliente
            ON CONFLICT (id_oficina, id_cliente) DO UPDATE
            SET ativo = TRUE,
                updated_at = excluded.updated_at';
    END IF;
END $migration$;

DO $migration$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_pedido_oficina_cliente_id_oficina_id_cliente'
    ) THEN
        ALTER TABLE pedido
            DROP CONSTRAINT "FK_pedido_oficina_cliente_id_oficina_id_cliente";
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'FK_pedido_cliente_oficina_id_oficina_id_cliente'
    ) THEN
        ALTER TABLE pedido
            ADD CONSTRAINT "FK_pedido_cliente_oficina_id_oficina_id_cliente"
            FOREIGN KEY (id_oficina, id_cliente)
            REFERENCES cliente_oficina (id_oficina, id_cliente)
            ON DELETE RESTRICT;
    END IF;
END $migration$;

CREATE INDEX IF NOT EXISTS "IX_cliente_oficina_id_cliente" ON cliente_oficina (id_cliente);
CREATE INDEX IF NOT EXISTS "IX_cliente_oficina_oficina_ativo_cliente" ON cliente_oficina (id_oficina, ativo, id_cliente);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260527164512_FixPedidoClienteOficinaFk', '9.0.9');

ALTER TABLE cliente_oficina
    ALTER COLUMN dados_permitidos
    SET DEFAULT '["Nome","Email","Cpf_Cnpj","Telefones","Veiculos"]';

UPDATE cliente_oficina
SET dados_permitidos = '["Nome","Email","Cpf_Cnpj","Telefones","Veiculos"]',
    updated_at = now()
WHERE ativo = TRUE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260527170500_FullAccessClienteOficinaVinculo', '9.0.9');

ALTER TABLE cliente_oficina
    DROP COLUMN IF EXISTS dados_permitidos;

ALTER TABLE compartilhamento_cliente
    DROP COLUMN IF EXISTS dados_permitidos;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260527173000_RemoveDadosPermitidosFromClienteLinks', '9.0.9');

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM cliente
        GROUP BY regexp_replace(coalesce(cpf_cnpj, ''), '[^0-9]', '', 'g')
        HAVING count(*) > 1
    ) THEN
        RAISE EXCEPTION 'Migration blocked: duplicate normalized CPF/CNPJ values exist in cliente.';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM cliente
        WHERE regexp_replace(coalesce(cpf_cnpj, ''), '[^0-9]', '', 'g')
              !~ '^([0-9]{11}|[0-9]{14})$'
    ) THEN
        RAISE EXCEPTION 'Migration blocked: invalid CPF/CNPJ values exist in cliente.';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM cliente
        WHERE nullif(btrim(cep), '') IS NOT NULL
          AND regexp_replace(cep, '[^0-9]', '', 'g') !~ '^[0-9]{8}$'
    ) THEN
        RAISE EXCEPTION 'Migration blocked: non-empty CEP values must normalize to exactly 8 digits.';
    END IF;

END $$;

CREATE TABLE auditoria_seguranca (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_cliente integer NULL,
    tipo_ator integer NOT NULL,
    id_ator integer NULL,
    evento integer NOT NULL,
    resultado integer NOT NULL,
    documento_hash varchar(64) NULL,
    contato_hash varchar(64) NULL,
    documento_mascarado varchar(32) NULL,
    contato_mascarado varchar(254) NULL,
    ip_address varchar(64) NULL,
    correlation_id varchar(128) NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_auditoria_seguranca" PRIMARY KEY (id),
    CONSTRAINT "FK_auditoria_seguranca_cliente_id_cliente"
        FOREIGN KEY (id_cliente) REFERENCES cliente(id) ON DELETE SET NULL,
    CONSTRAINT "CK_auditoria_seguranca_tipo_ator" CHECK (tipo_ator BETWEEN 0 AND 5),
    CONSTRAINT "CK_auditoria_seguranca_evento" CHECK (evento IN (2, 4, 5, 6, 7, 8, 9)),
    CONSTRAINT "CK_auditoria_seguranca_resultado" CHECK (resultado BETWEEN 1 AND 2)
);

CREATE INDEX "IX_auditoria_seguranca_id_cliente"
    ON auditoria_seguranca(id_cliente);
CREATE INDEX "IX_auditoria_seguranca_evento_created_at"
    ON auditoria_seguranca(evento, created_at);
CREATE INDEX "IX_auditoria_seguranca_documento_hash"
    ON auditoria_seguranca(documento_hash);

INSERT INTO auditoria_seguranca (
    id_cliente,
    tipo_ator,
    id_ator,
    evento,
    resultado,
    contato_hash,
    ip_address,
    correlation_id,
    created_at)
SELECT
    NULL,
    2,
    id_oficina,
    8,
    CASE WHEN sucesso THEN 1 ELSE 2 END,
    left(codigo_hash, 64),
    ip_address,
    left(motivo, 128),
    tentado_em
FROM compartilhamento_cliente_tentativa;

INSERT INTO auditoria_seguranca (
    id_cliente,
    tipo_ator,
    evento,
    resultado,
    contato_hash,
    correlation_id,
    created_at)
SELECT
    id_cliente,
    5,
    9,
    1,
    left(codigo_hash, 64),
    'compartilhamento-legado-desativado',
    now()
FROM compartilhamento_cliente;

DROP TABLE compartilhamento_cliente_tentativa;
DROP TABLE compartilhamento_cliente;

ALTER TABLE cliente ALTER COLUMN email TYPE varchar(254);
ALTER TABLE cliente ALTER COLUMN email DROP NOT NULL;
ALTER TABLE cliente ALTER COLUMN senha DROP NOT NULL;
ALTER TABLE cliente ALTER COLUMN rua DROP NOT NULL;
ALTER TABLE cliente ALTER COLUMN cidade DROP NOT NULL;
ALTER TABLE cliente ALTER COLUMN cep TYPE varchar(8)
    USING nullif(regexp_replace(cep, '[^0-9]', '', 'g'), '');
ALTER TABLE cliente ALTER COLUMN cep DROP NOT NULL;
ALTER TABLE cliente ALTER COLUMN bairro DROP NOT NULL;
ALTER TABLE cliente ALTER COLUMN estado DROP NOT NULL;
ALTER TABLE cliente ALTER COLUMN pais DROP NOT NULL;
ALTER TABLE cliente ALTER COLUMN complemento DROP NOT NULL;

UPDATE cliente
SET cpf_cnpj = regexp_replace(cpf_cnpj, '[^0-9]', '', 'g'),
    email = CASE
        WHEN nullif(btrim(email), '') IS NULL THEN NULL
        ELSE lower(btrim(email))
    END;

ALTER TABLE cliente
    ADD CONSTRAINT "CK_cliente_cpf_cnpj_normalizado"
    CHECK (cpf_cnpj ~ '^[0-9]{11}$|^[0-9]{14}$');
CREATE UNIQUE INDEX "IX_cliente_cpf_cnpj" ON cliente(cpf_cnpj);

CREATE TABLE cliente_conta (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    id_cliente integer NOT NULL,
    email_normalizado varchar(254) NOT NULL,
    password_hash varchar(255) NOT NULL,
    status integer NOT NULL,
    token_version integer NOT NULL DEFAULT 1,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_cliente_conta" PRIMARY KEY (id),
    CONSTRAINT "FK_cliente_conta_cliente_id_cliente"
        FOREIGN KEY (id_cliente) REFERENCES cliente(id) ON DELETE CASCADE,
    CONSTRAINT "CK_cliente_conta_token_version" CHECK (token_version >= 1),
    CONSTRAINT "CK_cliente_conta_status" CHECK (status BETWEEN 1 AND 2),
    CONSTRAINT "CK_cliente_conta_email_normalizado"
        CHECK (email_normalizado = lower(btrim(email_normalizado))
               AND position('@' in email_normalizado) > 1)
);

CREATE UNIQUE INDEX "IX_cliente_conta_id_cliente"
    ON cliente_conta(id_cliente);
CREATE UNIQUE INDEX "IX_cliente_conta_email_normalizado"
    ON cliente_conta(email_normalizado);

-- Credenciais de cliente legadas não são promovidas automaticamente.
-- O schema anterior não registra se o cadastro veio do cliente ou da oficina;
-- portanto, cada CPF legado permanece disponível para o cadastro direto.

CREATE TABLE cliente_contato (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    id_cliente integer NOT NULL,
    tipo integer NOT NULL,
    valor_normalizado varchar(254) NOT NULL,
    origem integer NOT NULL,
    verificado_em timestamp with time zone NULL,
    created_at timestamp with time zone NOT NULL,
    CONSTRAINT "PK_cliente_contato" PRIMARY KEY (id),
    CONSTRAINT "FK_cliente_contato_cliente_id_cliente"
        FOREIGN KEY (id_cliente) REFERENCES cliente(id) ON DELETE CASCADE,
    CONSTRAINT "CK_cliente_contato_tipo" CHECK (tipo BETWEEN 1 AND 2),
    CONSTRAINT "CK_cliente_contato_origem" CHECK (origem BETWEEN 1 AND 3),
    CONSTRAINT "CK_cliente_contato_valor_normalizado" CHECK (
        (tipo = 1
         AND valor_normalizado = lower(btrim(valor_normalizado))
         AND position('@' in valor_normalizado) > 1)
        OR (tipo = 2 AND valor_normalizado ~ '^[0-9]{10,13}$'))
);

CREATE UNIQUE INDEX "IX_cliente_contato_cliente_tipo_valor"
    ON cliente_contato(id_cliente, tipo, valor_normalizado);
CREATE INDEX "IX_cliente_contato_tipo_valor"
    ON cliente_contato(tipo, valor_normalizado);

INSERT INTO cliente_contato (
    id_cliente,
    tipo,
    valor_normalizado,
    origem,
    verificado_em,
    created_at)
SELECT
    id,
    1,
    lower(btrim(email)),
    3,
    NULL,
    now()
FROM cliente
WHERE nullif(btrim(email), '') IS NOT NULL
  AND position('@' in lower(btrim(email))) > 1
ON CONFLICT (id_cliente, tipo, valor_normalizado) DO NOTHING;


DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM oficina
        GROUP BY lower(btrim(email))
        HAVING count(*) > 1
    ) THEN
        RAISE EXCEPTION 'Migration blocked: duplicate oficina e-mails after trim/case normalization.';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM funcionario
        GROUP BY lower(btrim(email))
        HAVING count(*) > 1
    ) THEN
        RAISE EXCEPTION 'Migration blocked: duplicate funcionario e-mails after trim/case normalization.';
    END IF;
END $$;

UPDATE oficina
SET email = lower(btrim(email))
WHERE email IS DISTINCT FROM lower(btrim(email));

UPDATE funcionario
SET email = lower(btrim(email))
WHERE email IS DISTINCT FROM lower(btrim(email));

CREATE UNIQUE INDEX IF NOT EXISTS "UX_oficina_email_normalizado"
    ON oficina (lower(btrim(email)));

CREATE UNIQUE INDEX IF NOT EXISTS "UX_funcionario_email_normalizado"
    ON funcionario (lower(btrim(email)));

ALTER TABLE registro_servico ADD id_oficina integer;

UPDATE registro_servico AS registro
SET id_oficina = servico.id_oficina
FROM servico
WHERE registro.id_servico = servico.id
  AND servico.id_oficina IS NOT NULL;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM registro_servico
        WHERE id_oficina IS NULL
    ) THEN
        RAISE EXCEPTION 'Migration blocked: registro_servico rows without an identifiable oficina owner require manual correction.';
    END IF;
END $$;

ALTER TABLE registro_servico ALTER COLUMN id_oficina SET NOT NULL;

CREATE INDEX "IX_registro_servico_oficina_data" ON registro_servico (id_oficina, data_servico DESC);

ALTER TABLE registro_servico ADD CONSTRAINT "FK_registro_servico_oficina_id_oficina" FOREIGN KEY (id_oficina) REFERENCES oficina (id) ON DELETE RESTRICT;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260713150936_ClienteDirectRegistrationV1', '9.0.9');

ALTER TABLE cliente_oficina ADD revogado_em timestamp with time zone;

UPDATE cliente_oficina
SET revogado_em = updated_at
WHERE ativo = FALSE
  AND revogado_em IS NULL;

ALTER TABLE cliente_oficina ADD CONSTRAINT "CK_cliente_oficina_ativo_revogado" CHECK (NOT (ativo AND revogado_em IS NOT NULL));

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260713172020_ClienteLinkRevocationSafety', '9.0.9');

UPDATE veiculo_imagem
SET url = REPLACE(url, '/api/veiculos/', '/api/v1/veiculos/')
WHERE url LIKE '/api/veiculos/%';

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260716180124_NormalizeApiV1VehicleImageUrls', '9.0.9');

COMMIT;

