CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE TABLE cliente (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(100) NOT NULL,
        email character varying(100) NOT NULL,
        senha character varying(100) NOT NULL,
        cpf_cnpj character varying(14) NOT NULL,
        obs character varying(500),
        razao character varying(500),
        datanasc date,
        sexo integer NOT NULL,
        numero integer NOT NULL,
        rua character varying(500) NOT NULL,
        cidade character varying(500) NOT NULL,
        cep text NOT NULL,
        bairro character varying(500) NOT NULL,
        estado character varying(500) NOT NULL,
        pais character varying(500) NOT NULL,
        complemento character varying(500) NOT NULL,
        tipocliente integer NOT NULL,
        situacao integer NOT NULL,
        CONSTRAINT "PK_cliente" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE TABLE oficina (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(100) NOT NULL,
        cnpj text NOT NULL,
        email character varying(100) NOT NULL,
        numero integer NOT NULL,
        rua character varying(200) NOT NULL,
        cidade character varying(100) NOT NULL,
        cep integer NOT NULL,
        bairro character varying(100) NOT NULL,
        estado character varying(50) NOT NULL,
        pais character varying(50) NOT NULL,
        complemento character varying(200),
        senha text NOT NULL,
        situacao integer NOT NULL,
        CONSTRAINT "PK_oficina" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE TABLE servico (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(100) NOT NULL,
        descricao text NOT NULL,
        valor double precision NOT NULL,
        garantia date NOT NULL,
        CONSTRAINT "PK_servico" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE TABLE compartilhamento_cliente (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        id_cliente integer NOT NULL,
        codigo_hash character varying(128) NOT NULL,
        dados_permitidos text NOT NULL,
        expira_em timestamp with time zone NOT NULL,
        usado_em timestamp with time zone,
        ativo boolean NOT NULL,
        CONSTRAINT "PK_compartilhamento_cliente" PRIMARY KEY (id),
        CONSTRAINT "FK_compartilhamento_cliente_cliente_id_cliente" FOREIGN KEY (id_cliente) REFERENCES cliente (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE TABLE veiculo (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(100) NOT NULL,
        tipo character varying(50) NOT NULL,
        placa character varying(8) NOT NULL,
        chassi character varying(17) NOT NULL,
        ano integer NOT NULL,
        quilometragem integer NOT NULL,
        combustivel character varying(30) NOT NULL,
        seguro character varying(100),
        cor text NOT NULL,
        status integer NOT NULL,
        id_cliente integer NOT NULL,
        CONSTRAINT "PK_veiculo" PRIMARY KEY (id),
        CONSTRAINT "AK_veiculo_id_id_cliente" UNIQUE (id, id_cliente),
        CONSTRAINT "FK_veiculo_cliente_id_cliente" FOREIGN KEY (id_cliente) REFERENCES cliente (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE TABLE compartilhamento_cliente_tentativa (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        id_oficina integer NOT NULL,
        codigo_hash character varying(128) NOT NULL,
        ip_address character varying(64),
        sucesso boolean NOT NULL,
        motivo character varying(64) NOT NULL,
        tentado_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_compartilhamento_cliente_tentativa" PRIMARY KEY (id),
        CONSTRAINT "FK_compartilhamento_cliente_tentativa_oficina_id_oficina" FOREIGN KEY (id_oficina) REFERENCES oficina (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE TABLE funcionario (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(100) NOT NULL,
        cpf character varying(12) NOT NULL,
        cargo character varying(100) NOT NULL,
        email character varying(100) NOT NULL,
        senha text NOT NULL,
        situacao integer NOT NULL,
        id_oficina integer,
        CONSTRAINT "PK_funcionario" PRIMARY KEY (id),
        CONSTRAINT "FK_funcionario_oficina_id_oficina" FOREIGN KEY (id_oficina) REFERENCES oficina (id) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE TABLE cliente_oficina (
        id_oficina integer NOT NULL,
        id_cliente integer NOT NULL,
        ativo boolean NOT NULL,
        dados_permitidos text NOT NULL,
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_cliente_oficina" PRIMARY KEY (id_oficina, id_cliente),
        CONSTRAINT "FK_cliente_oficina_cliente_id_cliente" FOREIGN KEY (id_cliente) REFERENCES cliente (id) ON DELETE CASCADE,
        CONSTRAINT "FK_cliente_oficina_oficina_id_oficina" FOREIGN KEY (id_oficina) REFERENCES oficina (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE TABLE marca (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(100) NOT NULL,
        "desc" character varying(500),
        tipomarca character varying(50) NOT NULL,
        "VeiculoId" integer,
        CONSTRAINT "PK_marca" PRIMARY KEY (id),
        CONSTRAINT "FK_marca_veiculo_VeiculoId" FOREIGN KEY ("VeiculoId") REFERENCES veiculo (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE TABLE registro_servico (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        id_veiculo integer NOT NULL,
        id_servico integer,
        data_servico timestamp with time zone NOT NULL,
        descricao text,
        quilometragem integer NOT NULL,
        responsavel text,
        CONSTRAINT "PK_registro_servico" PRIMARY KEY (id),
        CONSTRAINT "FK_registro_servico_servico_id_servico" FOREIGN KEY (id_servico) REFERENCES servico (id) ON DELETE SET NULL,
        CONSTRAINT "FK_registro_servico_veiculo_id_veiculo" FOREIGN KEY (id_veiculo) REFERENCES veiculo (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE TABLE funcionario_servico (
        "idFuncionario" integer NOT NULL,
        "idServico" integer NOT NULL,
        tempodec text,
        CONSTRAINT "PK_funcionario_servico" PRIMARY KEY ("idFuncionario", "idServico"),
        CONSTRAINT "FK_funcionario_servico_funcionario_idFuncionario" FOREIGN KEY ("idFuncionario") REFERENCES funcionario (id) ON DELETE CASCADE,
        CONSTRAINT "FK_funcionario_servico_servico_idServico" FOREIGN KEY ("idServico") REFERENCES servico (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE TABLE telefone (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        numero character varying(9) NOT NULL,
        ddd integer NOT NULL,
        clienteid integer NOT NULL,
        "FuncionarioId" integer,
        "OficinaId" integer,
        CONSTRAINT "PK_telefone" PRIMARY KEY (id),
        CONSTRAINT "FK_telefone_cliente_clienteid" FOREIGN KEY (clienteid) REFERENCES cliente (id) ON DELETE CASCADE,
        CONSTRAINT "FK_telefone_funcionario_FuncionarioId" FOREIGN KEY ("FuncionarioId") REFERENCES funcionario (id),
        CONSTRAINT "FK_telefone_oficina_OficinaId" FOREIGN KEY ("OficinaId") REFERENCES oficina (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE TABLE pedido (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        id_cliente integer NOT NULL,
        id_funcionario integer NOT NULL,
        id_oficina integer NOT NULL,
        id_veiculo integer NOT NULL,
        "valorTotal" real NOT NULL,
        "descontoReais" real NOT NULL,
        "descontoPorcentagem" real NOT NULL,
        "descontoTotalReais" real NOT NULL,
        "descontoServicoPorcentagem" real NOT NULL,
        "descontoServicoReais" real NOT NULL,
        "descontoPecaPorcentagem" real NOT NULL,
        "descontoPecaReais" real NOT NULL,
        observacao character varying(500),
        "dataInicio" date NOT NULL,
        "dataFim" date NOT NULL,
        CONSTRAINT "PK_pedido" PRIMARY KEY (id),
        CONSTRAINT "FK_pedido_cliente_id_cliente" FOREIGN KEY (id_cliente) REFERENCES cliente (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_pedido_funcionario_id_funcionario" FOREIGN KEY (id_funcionario) REFERENCES funcionario (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_pedido_cliente_oficina_id_oficina_id_cliente" FOREIGN KEY (id_oficina, id_cliente) REFERENCES cliente_oficina (id_oficina, id_cliente) ON DELETE RESTRICT,
        CONSTRAINT "FK_pedido_oficina_id_oficina" FOREIGN KEY (id_oficina) REFERENCES oficina (id) ON DELETE RESTRICT,
        CONSTRAINT "FK_pedido_veiculo_id_veiculo_id_cliente" FOREIGN KEY (id_veiculo, id_cliente) REFERENCES veiculo (id, id_cliente) ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE TABLE peca (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        nome character varying(100) NOT NULL,
        tipo character varying(100) NOT NULL,
        descricao character varying(500),
        valor real NOT NULL,
        quantidade integer NOT NULL,
        garantia date NOT NULL,
        unidade integer NOT NULL,
        idmarca integer NOT NULL,
        "dataAquisicao" date NOT NULL,
        fornecedor character varying(100) NOT NULL,
        CONSTRAINT "PK_peca" PRIMARY KEY (id),
        CONSTRAINT "FK_peca_marca_idmarca" FOREIGN KEY (idmarca) REFERENCES marca (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE TABLE peca_substituida (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        id_registro_servico integer NOT NULL,
        nome text,
        quantidade integer NOT NULL,
        observacao text,
        CONSTRAINT "PK_peca_substituida" PRIMARY KEY (id),
        CONSTRAINT "FK_peca_substituida_registro_servico_id_registro_servico" FOREIGN KEY (id_registro_servico) REFERENCES registro_servico (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE TABLE pedido_servico (
        "idPedido" integer NOT NULL,
        "idServico" integer NOT NULL,
        "quantVezes" integer NOT NULL,
        CONSTRAINT "PK_pedido_servico" PRIMARY KEY ("idPedido", "idServico"),
        CONSTRAINT "FK_pedido_servico_pedido_idPedido" FOREIGN KEY ("idPedido") REFERENCES pedido (id) ON DELETE CASCADE,
        CONSTRAINT "FK_pedido_servico_servico_idServico" FOREIGN KEY ("idServico") REFERENCES servico (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE TABLE pedido_peca (
        idpedido integer NOT NULL,
        idpeca integer NOT NULL,
        quantidade integer NOT NULL,
        datainstalacao date NOT NULL,
        estado text,
        observacao text,
        CONSTRAINT "PK_pedido_peca" PRIMARY KEY (idpedido, idpeca),
        CONSTRAINT "FK_pedido_peca_peca_idpeca" FOREIGN KEY (idpeca) REFERENCES peca (id) ON DELETE CASCADE,
        CONSTRAINT "FK_pedido_peca_pedido_idpedido" FOREIGN KEY (idpedido) REFERENCES pedido (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE UNIQUE INDEX "IX_compartilhamento_cliente_codigo_hash" ON compartilhamento_cliente (codigo_hash) WHERE ativo AND usado_em IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE INDEX "IX_compartilhamento_cliente_id_cliente" ON compartilhamento_cliente (id_cliente);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE INDEX "IX_compartilhamento_cliente_tentativa_id_oficina_ip_address_te~" ON compartilhamento_cliente_tentativa (id_oficina, ip_address, tentado_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE INDEX "IX_funcionario_id_oficina" ON funcionario (id_oficina);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE INDEX "IX_funcionario_servico_idServico" ON funcionario_servico ("idServico");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE INDEX "IX_marca_VeiculoId" ON marca ("VeiculoId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE INDEX "IX_cliente_oficina_id_cliente" ON cliente_oficina (id_cliente);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE INDEX "IX_peca_idmarca" ON peca (idmarca);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE INDEX "IX_peca_substituida_id_registro_servico" ON peca_substituida (id_registro_servico);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE INDEX "IX_pedido_id_cliente" ON pedido (id_cliente);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE INDEX "IX_pedido_id_funcionario" ON pedido (id_funcionario);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE INDEX "IX_pedido_id_oficina_id_cliente" ON pedido (id_oficina, id_cliente);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE INDEX "IX_pedido_id_veiculo_id_cliente" ON pedido (id_veiculo, id_cliente);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE INDEX "IX_pedido_peca_idpeca" ON pedido_peca (idpeca);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE INDEX "IX_pedido_servico_idServico" ON pedido_servico ("idServico");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE INDEX "IX_registro_servico_id_servico" ON registro_servico (id_servico);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE INDEX "IX_registro_servico_id_veiculo" ON registro_servico (id_veiculo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE INDEX "IX_telefone_clienteid" ON telefone (clienteid);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE INDEX "IX_telefone_FuncionarioId" ON telefone ("FuncionarioId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE INDEX "IX_telefone_OficinaId" ON telefone ("OficinaId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    CREATE INDEX "IX_veiculo_id_cliente" ON veiculo (id_cliente);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505161052_Teste') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260505161052_Teste', '9.0.9');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505173656_Teste2') THEN
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1
            FROM (
                SELECT regexp_replace(coalesce(cpf_cnpj, ''), '\D', '', 'g') AS documento
                FROM cliente
            ) normalizados
            WHERE documento <> ''
            GROUP BY documento
            HAVING count(*) > 1
        ) THEN
            RAISE EXCEPTION 'Não foi possível criar índice único em cliente.cpf_cnpj: existem CPF/CNPJ duplicados após normalização.';
        END IF;
    END $$;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505173656_Teste2') THEN
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1
            FROM (
                SELECT lower(trim(coalesce(email, ''))) AS email_normalizado
                FROM cliente
            ) normalizados
            WHERE email_normalizado <> ''
            GROUP BY email_normalizado
            HAVING count(*) > 1
        ) THEN
            RAISE EXCEPTION 'Não foi possível criar índice único em cliente.email: existem e-mails duplicados após normalização.';
        END IF;
    END $$;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505173656_Teste2') THEN
    CREATE UNIQUE INDEX "IX_cliente_cpf_cnpj_normalizado"
    ON cliente (regexp_replace(coalesce(cpf_cnpj, ''), '\D', '', 'g'));
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505173656_Teste2') THEN
    CREATE UNIQUE INDEX "IX_cliente_email_normalizado"
    ON cliente (lower(trim(coalesce(email, ''))));
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260505173656_Teste2') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260505173656_Teste2', '9.0.9');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506170000_ProductionSecurityHardening') THEN
    ALTER TABLE funcionario ADD role character varying(30) NOT NULL DEFAULT 'Funcionario';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506170000_ProductionSecurityHardening') THEN
    ALTER TABLE servico ADD id_oficina integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506170000_ProductionSecurityHardening') THEN
    ALTER TABLE peca ADD id_oficina integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506170000_ProductionSecurityHardening') THEN
    CREATE INDEX "IX_servico_id_oficina" ON servico (id_oficina);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506170000_ProductionSecurityHardening') THEN
    CREATE INDEX "IX_peca_id_oficina" ON peca (id_oficina);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506170000_ProductionSecurityHardening') THEN
    ALTER TABLE peca ADD CONSTRAINT "FK_peca_oficina_id_oficina" FOREIGN KEY (id_oficina) REFERENCES oficina (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506170000_ProductionSecurityHardening') THEN
    ALTER TABLE servico ADD CONSTRAINT "FK_servico_oficina_id_oficina" FOREIGN KEY (id_oficina) REFERENCES oficina (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260506170000_ProductionSecurityHardening') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260506170000_ProductionSecurityHardening', '9.0.9');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260507192929_TesteT') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260507192929_TesteT', '9.0.9');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    CREATE TABLE IF NOT EXISTS cliente_oficina (
        id_oficina integer NOT NULL,
        id_cliente integer NOT NULL,
        ativo boolean NOT NULL DEFAULT TRUE,
        dados_permitidos text NOT NULL DEFAULT '["nome"]',
        created_at timestamp with time zone NOT NULL DEFAULT now(),
        updated_at timestamp with time zone NOT NULL DEFAULT now()
    );

    ALTER TABLE cliente_oficina
        ADD COLUMN IF NOT EXISTS ativo boolean NOT NULL DEFAULT TRUE,
        ADD COLUMN IF NOT EXISTS dados_permitidos text NOT NULL DEFAULT '["nome"]',
        ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT now(),
        ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT now();

    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'PK_cliente_oficina'
        ) THEN
            ALTER TABLE cliente_oficina
                ADD CONSTRAINT "PK_cliente_oficina" PRIMARY KEY (id_oficina, id_cliente);
        END IF;

        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'FK_cliente_oficina_cliente_id_cliente'
        ) THEN
            ALTER TABLE cliente_oficina
                ADD CONSTRAINT "FK_cliente_oficina_cliente_id_cliente"
                FOREIGN KEY (id_cliente) REFERENCES cliente (id) ON DELETE CASCADE;
        END IF;

        IF NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'FK_cliente_oficina_oficina_id_oficina'
        ) THEN
            ALTER TABLE cliente_oficina
                ADD CONSTRAINT "FK_cliente_oficina_oficina_id_oficina"
                FOREIGN KEY (id_oficina) REFERENCES oficina (id) ON DELETE CASCADE;
        END IF;
    END $$;

    CREATE INDEX IF NOT EXISTS "IX_cliente_oficina_id_cliente" ON cliente_oficina (id_cliente);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    ALTER TABLE peca DROP CONSTRAINT "FK_peca_marca_idmarca";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    ALTER TABLE pedido_peca DROP CONSTRAINT "FK_pedido_peca_peca_idpeca";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    ALTER TABLE pedido_servico DROP CONSTRAINT "FK_pedido_servico_servico_idServico";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    ALTER TABLE registro_servico DROP CONSTRAINT "FK_registro_servico_veiculo_id_veiculo";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    ALTER TABLE servico ALTER COLUMN valor TYPE numeric(18,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    ALTER TABLE peca ALTER COLUMN valor TYPE numeric(18,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    ALTER TABLE pedido ALTER COLUMN "valorTotal" TYPE numeric(18,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    ALTER TABLE pedido ALTER COLUMN "descontoTotalReais" TYPE numeric(18,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    ALTER TABLE pedido ALTER COLUMN "descontoServicoReais" TYPE numeric(18,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    ALTER TABLE pedido ALTER COLUMN "descontoReais" TYPE numeric(18,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    ALTER TABLE pedido ALTER COLUMN "descontoPecaReais" TYPE numeric(18,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    ALTER TABLE pedido ALTER COLUMN "descontoServicoPorcentagem" TYPE numeric(5,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    ALTER TABLE pedido ALTER COLUMN "descontoPorcentagem" TYPE numeric(5,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    ALTER TABLE pedido ALTER COLUMN "descontoPecaPorcentagem" TYPE numeric(5,2);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    CREATE INDEX "IX_servico_id_oficina_nome" ON servico (id_oficina, nome);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    CREATE INDEX "IX_registro_servico_veiculo_data" ON registro_servico (id_veiculo, data_servico DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    CREATE INDEX "IX_peca_id_oficina_nome" ON peca (id_oficina, nome);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    CREATE INDEX "IX_pedido_id_veiculo_dataInicio" ON pedido (id_veiculo, "dataInicio" DESC);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    CREATE UNIQUE INDEX "IX_oficina_cnpj" ON oficina (cnpj);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    CREATE UNIQUE INDEX "IX_oficina_email" ON oficina (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    CREATE UNIQUE INDEX "IX_funcionario_cpf" ON funcionario (cpf);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    CREATE UNIQUE INDEX "IX_funcionario_email" ON funcionario (email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    CREATE INDEX "IX_funcionario_id_oficina_nome" ON funcionario (id_oficina, nome);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_funcionario_email_normalized" ON funcionario (lower(btrim(email)));
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_funcionario_cpf_normalized" ON funcionario (regexp_replace(cpf, '[^0-9]', '', 'g'));
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_oficina_email_normalized" ON oficina (lower(btrim(email)));
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    CREATE UNIQUE INDEX IF NOT EXISTS "IX_oficina_cnpj_normalized" ON oficina (regexp_replace(cnpj, '[^0-9]', '', 'g'));
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    CREATE INDEX IF NOT EXISTS "IX_cliente_oficina_oficina_ativo_cliente" ON cliente_oficina (id_oficina, ativo, id_cliente);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    ALTER TABLE peca ADD CONSTRAINT "FK_peca_marca_idmarca" FOREIGN KEY (idmarca) REFERENCES marca (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    ALTER TABLE pedido_peca ADD CONSTRAINT "FK_pedido_peca_peca_idpeca" FOREIGN KEY (idpeca) REFERENCES peca (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    ALTER TABLE pedido_servico ADD CONSTRAINT "FK_pedido_servico_servico_idServico" FOREIGN KEY ("idServico") REFERENCES servico (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    ALTER TABLE registro_servico ADD CONSTRAINT "FK_registro_servico_veiculo_id_veiculo" FOREIGN KEY (id_veiculo) REFERENCES veiculo (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508120000_MoneyPrecisionIdentityIndexes') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260508120000_MoneyPrecisionIdentityIndexes', '9.0.9');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508133248_SyncModelSnapshot') THEN
    DROP INDEX "IX_servico_id_oficina";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508133248_SyncModelSnapshot') THEN
    DROP INDEX "IX_registro_servico_id_veiculo";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508133248_SyncModelSnapshot') THEN
    DROP INDEX "IX_peca_id_oficina";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508133248_SyncModelSnapshot') THEN
    DROP INDEX "IX_funcionario_id_oficina";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508133248_SyncModelSnapshot') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260508133248_SyncModelSnapshot', '9.0.9');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520001503_inicial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260520001503_inicial', '9.0.9');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260521191400_AddVeiculoImagens') THEN
    CREATE TABLE veiculo_imagem (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        id_veiculo integer NOT NULL,
        url character varying(300) NOT NULL,
        nome_arquivo character varying(150) NOT NULL,
        nome_original character varying(255) NOT NULL,
        content_type character varying(100) NOT NULL,
        tamanho_bytes bigint NOT NULL,
        criado_em timestamp with time zone NOT NULL,
        CONSTRAINT "PK_veiculo_imagem" PRIMARY KEY (id),
        CONSTRAINT "FK_veiculo_imagem_veiculo_id_veiculo" FOREIGN KEY (id_veiculo) REFERENCES veiculo (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260521191400_AddVeiculoImagens') THEN
    CREATE UNIQUE INDEX "IX_veiculo_imagem_nome_arquivo" ON veiculo_imagem (nome_arquivo);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260521191400_AddVeiculoImagens') THEN
    CREATE INDEX "IX_veiculo_imagem_veiculo_criado_em" ON veiculo_imagem (id_veiculo, criado_em);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260521191400_AddVeiculoImagens') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260521191400_AddVeiculoImagens', '9.0.9');
    END IF;
END $EF$;
COMMIT;

