using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SIGO.Migrations
{
    /// <inheritdoc />
    public partial class ClienteDirectRegistrationV1 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                """
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM cliente
                        GROUP BY regexp_replace(coalesce(cpf_cnpj, ''), '[^0-9]', '', 'g')
                        HAVING count(*) > 1
                    ) THEN
                        RAISE EXCEPTION 'Migration blocked: duplicate normalized CPF/CNPJ values exist in cliente.';
                    END IF;

                    IF EXISTS (
                        SELECT 1
                        FROM cliente
                        WHERE regexp_replace(coalesce(cpf_cnpj, ''), '[^0-9]', '', 'g')
                              !~ '^([0-9]{11}|[0-9]{14})$'
                    ) THEN
                        RAISE EXCEPTION 'Migration blocked: invalid CPF/CNPJ values exist in cliente.';
                    END IF;

                    IF EXISTS (
                        SELECT 1
                        FROM cliente
                        WHERE nullif(btrim(cep), '') IS NOT NULL
                          AND regexp_replace(cep, '[^0-9]', '', 'g') !~ '^[0-9]{8}$'
                    ) THEN
                        RAISE EXCEPTION 'Migration blocked: non-empty CEP values must normalize to exactly 8 digits.';
                    END IF;

                END $$;

                CREATE TABLE auditoria_seguranca (
                    id bigint GENERATED BY DEFAULT AS IDENTITY,
                    id_cliente integer NULL,
                    tipo_ator integer NOT NULL,
                    id_ator integer NULL,
                    evento integer NOT NULL,
                    resultado integer NOT NULL,
                    documento_hash varchar(64) NULL,
                    contato_hash varchar(64) NULL,
                    documento_mascarado varchar(32) NULL,
                    contato_mascarado varchar(254) NULL,
                    ip_address varchar(64) NULL,
                    correlation_id varchar(128) NULL,
                    created_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_auditoria_seguranca" PRIMARY KEY (id),
                    CONSTRAINT "FK_auditoria_seguranca_cliente_id_cliente"
                        FOREIGN KEY (id_cliente) REFERENCES cliente(id) ON DELETE SET NULL,
                    CONSTRAINT "CK_auditoria_seguranca_tipo_ator" CHECK (tipo_ator BETWEEN 0 AND 5),
                    CONSTRAINT "CK_auditoria_seguranca_evento" CHECK (evento IN (2, 4, 5, 6, 7, 8, 9)),
                    CONSTRAINT "CK_auditoria_seguranca_resultado" CHECK (resultado BETWEEN 1 AND 2)
                );

                CREATE INDEX "IX_auditoria_seguranca_id_cliente"
                    ON auditoria_seguranca(id_cliente);
                CREATE INDEX "IX_auditoria_seguranca_evento_created_at"
                    ON auditoria_seguranca(evento, created_at);
                CREATE INDEX "IX_auditoria_seguranca_documento_hash"
                    ON auditoria_seguranca(documento_hash);

                INSERT INTO auditoria_seguranca (
                    id_cliente,
                    tipo_ator,
                    id_ator,
                    evento,
                    resultado,
                    contato_hash,
                    ip_address,
                    correlation_id,
                    created_at)
                SELECT
                    NULL,
                    2,
                    id_oficina,
                    8,
                    CASE WHEN sucesso THEN 1 ELSE 2 END,
                    left(codigo_hash, 64),
                    ip_address,
                    left(motivo, 128),
                    tentado_em
                FROM compartilhamento_cliente_tentativa;

                INSERT INTO auditoria_seguranca (
                    id_cliente,
                    tipo_ator,
                    evento,
                    resultado,
                    contato_hash,
                    correlation_id,
                    created_at)
                SELECT
                    id_cliente,
                    5,
                    9,
                    1,
                    left(codigo_hash, 64),
                    'compartilhamento-legado-desativado',
                    now()
                FROM compartilhamento_cliente;

                DROP TABLE compartilhamento_cliente_tentativa;
                DROP TABLE compartilhamento_cliente;

                ALTER TABLE cliente ALTER COLUMN email TYPE varchar(254);
                ALTER TABLE cliente ALTER COLUMN email DROP NOT NULL;
                ALTER TABLE cliente ALTER COLUMN senha DROP NOT NULL;
                ALTER TABLE cliente ALTER COLUMN rua DROP NOT NULL;
                ALTER TABLE cliente ALTER COLUMN cidade DROP NOT NULL;
                ALTER TABLE cliente ALTER COLUMN cep TYPE varchar(8)
                    USING nullif(regexp_replace(cep, '[^0-9]', '', 'g'), '');
                ALTER TABLE cliente ALTER COLUMN cep DROP NOT NULL;
                ALTER TABLE cliente ALTER COLUMN bairro DROP NOT NULL;
                ALTER TABLE cliente ALTER COLUMN estado DROP NOT NULL;
                ALTER TABLE cliente ALTER COLUMN pais DROP NOT NULL;
                ALTER TABLE cliente ALTER COLUMN complemento DROP NOT NULL;

                UPDATE cliente
                SET cpf_cnpj = regexp_replace(cpf_cnpj, '[^0-9]', '', 'g'),
                    email = CASE
                        WHEN nullif(btrim(email), '') IS NULL THEN NULL
                        ELSE lower(btrim(email))
                    END;

                ALTER TABLE cliente
                    ADD CONSTRAINT "CK_cliente_cpf_cnpj_normalizado"
                    CHECK (cpf_cnpj ~ '^[0-9]{11}$|^[0-9]{14}$');
                CREATE UNIQUE INDEX "IX_cliente_cpf_cnpj" ON cliente(cpf_cnpj);

                CREATE TABLE cliente_conta (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    id_cliente integer NOT NULL,
                    email_normalizado varchar(254) NOT NULL,
                    password_hash varchar(255) NOT NULL,
                    status integer NOT NULL,
                    token_version integer NOT NULL DEFAULT 1,
                    created_at timestamp with time zone NOT NULL,
                    updated_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_cliente_conta" PRIMARY KEY (id),
                    CONSTRAINT "FK_cliente_conta_cliente_id_cliente"
                        FOREIGN KEY (id_cliente) REFERENCES cliente(id) ON DELETE CASCADE,
                    CONSTRAINT "CK_cliente_conta_token_version" CHECK (token_version >= 1),
                    CONSTRAINT "CK_cliente_conta_status" CHECK (status BETWEEN 1 AND 2),
                    CONSTRAINT "CK_cliente_conta_email_normalizado"
                        CHECK (email_normalizado = lower(btrim(email_normalizado))
                               AND position('@' in email_normalizado) > 1)
                );

                CREATE UNIQUE INDEX "IX_cliente_conta_id_cliente"
                    ON cliente_conta(id_cliente);
                CREATE UNIQUE INDEX "IX_cliente_conta_email_normalizado"
                    ON cliente_conta(email_normalizado);

                -- Credenciais de cliente legadas não são promovidas automaticamente.
                -- O schema anterior não registra se o cadastro veio do cliente ou da oficina;
                -- portanto, cada CPF legado permanece disponível para o cadastro direto.

                CREATE TABLE cliente_contato (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    id_cliente integer NOT NULL,
                    tipo integer NOT NULL,
                    valor_normalizado varchar(254) NOT NULL,
                    origem integer NOT NULL,
                    verificado_em timestamp with time zone NULL,
                    created_at timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_cliente_contato" PRIMARY KEY (id),
                    CONSTRAINT "FK_cliente_contato_cliente_id_cliente"
                        FOREIGN KEY (id_cliente) REFERENCES cliente(id) ON DELETE CASCADE,
                    CONSTRAINT "CK_cliente_contato_tipo" CHECK (tipo BETWEEN 1 AND 2),
                    CONSTRAINT "CK_cliente_contato_origem" CHECK (origem BETWEEN 1 AND 3),
                    CONSTRAINT "CK_cliente_contato_valor_normalizado" CHECK (
                        (tipo = 1
                         AND valor_normalizado = lower(btrim(valor_normalizado))
                         AND position('@' in valor_normalizado) > 1)
                        OR (tipo = 2 AND valor_normalizado ~ '^[0-9]{10,13}$'))
                );

                CREATE UNIQUE INDEX "IX_cliente_contato_cliente_tipo_valor"
                    ON cliente_contato(id_cliente, tipo, valor_normalizado);
                CREATE INDEX "IX_cliente_contato_tipo_valor"
                    ON cliente_contato(tipo, valor_normalizado);

                INSERT INTO cliente_contato (
                    id_cliente,
                    tipo,
                    valor_normalizado,
                    origem,
                    verificado_em,
                    created_at)
                SELECT
                    id,
                    1,
                    lower(btrim(email)),
                    3,
                    NULL,
                    now()
                FROM cliente
                WHERE nullif(btrim(email), '') IS NOT NULL
                  AND position('@' in lower(btrim(email))) > 1
                ON CONFLICT (id_cliente, tipo, valor_normalizado) DO NOTHING;

                """);

            migrationBuilder.Sql(
                """
                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM oficina
                        GROUP BY lower(btrim(email))
                        HAVING count(*) > 1
                    ) THEN
                        RAISE EXCEPTION 'Migration blocked: duplicate oficina e-mails after trim/case normalization.';
                    END IF;

                    IF EXISTS (
                        SELECT 1
                        FROM funcionario
                        GROUP BY lower(btrim(email))
                        HAVING count(*) > 1
                    ) THEN
                        RAISE EXCEPTION 'Migration blocked: duplicate funcionario e-mails after trim/case normalization.';
                    END IF;
                END $$;

                UPDATE oficina
                SET email = lower(btrim(email))
                WHERE email IS DISTINCT FROM lower(btrim(email));

                UPDATE funcionario
                SET email = lower(btrim(email))
                WHERE email IS DISTINCT FROM lower(btrim(email));

                CREATE UNIQUE INDEX IF NOT EXISTS "UX_oficina_email_normalizado"
                    ON oficina (lower(btrim(email)));

                CREATE UNIQUE INDEX IF NOT EXISTS "UX_funcionario_email_normalizado"
                    ON funcionario (lower(btrim(email)));
                """);

            migrationBuilder.AddColumn<int>(
                name: "id_oficina",
                table: "registro_servico",
                type: "integer",
                nullable: true);

            migrationBuilder.Sql(
                """
                UPDATE registro_servico AS registro
                SET id_oficina = servico.id_oficina
                FROM servico
                WHERE registro.id_servico = servico.id
                  AND servico.id_oficina IS NOT NULL;

                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM registro_servico
                        WHERE id_oficina IS NULL
                    ) THEN
                        RAISE EXCEPTION 'Migration blocked: registro_servico rows without an identifiable oficina owner require manual correction.';
                    END IF;
                END $$;
                """);

            migrationBuilder.AlterColumn<int>(
                name: "id_oficina",
                table: "registro_servico",
                type: "integer",
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_registro_servico_oficina_data",
                table: "registro_servico",
                columns: new[] { "id_oficina", "data_servico" },
                descending: new[] { false, true });

            migrationBuilder.AddForeignKey(
                name: "FK_registro_servico_oficina_id_oficina",
                table: "registro_servico",
                column: "id_oficina",
                principalTable: "oficina",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_registro_servico_oficina_id_oficina",
                table: "registro_servico");

            migrationBuilder.DropIndex(
                name: "IX_registro_servico_oficina_data",
                table: "registro_servico");

            migrationBuilder.DropColumn(
                name: "id_oficina",
                table: "registro_servico");

            migrationBuilder.Sql(
                """
                DROP INDEX IF EXISTS "UX_funcionario_email_normalizado";
                DROP INDEX IF EXISTS "UX_oficina_email_normalizado";
                """);

            migrationBuilder.Sql(
                """
                CREATE TABLE compartilhamento_cliente (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    id_cliente integer NOT NULL,
                    codigo_hash varchar(128) NOT NULL,
                    expira_em timestamp with time zone NOT NULL,
                    usado_em timestamp with time zone NULL,
                    ativo boolean NOT NULL,
                    CONSTRAINT "PK_compartilhamento_cliente" PRIMARY KEY (id),
                    CONSTRAINT "FK_compartilhamento_cliente_cliente_id_cliente"
                        FOREIGN KEY (id_cliente) REFERENCES cliente(id) ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX "IX_compartilhamento_cliente_codigo_hash"
                    ON compartilhamento_cliente(codigo_hash)
                    WHERE ativo AND usado_em IS NULL;
                CREATE INDEX "IX_compartilhamento_cliente_id_cliente"
                    ON compartilhamento_cliente(id_cliente);

                CREATE TABLE compartilhamento_cliente_tentativa (
                    id integer GENERATED BY DEFAULT AS IDENTITY,
                    id_oficina integer NOT NULL,
                    codigo_hash varchar(128) NOT NULL,
                    ip_address varchar(64) NULL,
                    sucesso boolean NOT NULL,
                    motivo varchar(64) NOT NULL,
                    tentado_em timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_compartilhamento_cliente_tentativa" PRIMARY KEY (id),
                    CONSTRAINT "FK_compartilhamento_cliente_tentativa_oficina_id_oficina"
                        FOREIGN KEY (id_oficina) REFERENCES oficina(id) ON DELETE CASCADE
                );

                CREATE INDEX "IX_compartilhamento_cliente_tentativa_id_oficina_ip_address_te~"
                    ON compartilhamento_cliente_tentativa(id_oficina, ip_address, tentado_em);

                DO $$
                BEGIN
                    IF EXISTS (
                        SELECT 1
                        FROM cliente AS c
                        LEFT JOIN cliente_conta AS cc ON cc.id_cliente = c.id
                        WHERE length(coalesce(cc.email_normalizado, c.email, '')) > 100
                           OR length(coalesce(cc.password_hash, c.senha, '')) > 100
                    ) THEN
                        RAISE EXCEPTION 'Rollback blocked: account credentials exceed the legacy 100-character columns.';
                    END IF;
                END $$;

                UPDATE cliente AS c
                SET email = cc.email_normalizado,
                    senha = cc.password_hash
                FROM cliente_conta AS cc
                WHERE cc.id_cliente = c.id;

                DROP TABLE cliente_contato;
                DROP TABLE cliente_conta;
                DROP TABLE auditoria_seguranca;

                DROP INDEX "IX_cliente_cpf_cnpj";
                ALTER TABLE cliente DROP CONSTRAINT "CK_cliente_cpf_cnpj_normalizado";

                UPDATE cliente
                SET email = coalesce(email, ''),
                    senha = coalesce(senha, ''),
                    rua = coalesce(rua, ''),
                    cidade = coalesce(cidade, ''),
                    cep = coalesce(cep, ''),
                    bairro = coalesce(bairro, ''),
                    estado = coalesce(estado, ''),
                    pais = coalesce(pais, ''),
                    complemento = coalesce(complemento, '');

                ALTER TABLE cliente ALTER COLUMN email TYPE varchar(100);
                ALTER TABLE cliente ALTER COLUMN email SET NOT NULL;
                ALTER TABLE cliente ALTER COLUMN senha SET NOT NULL;
                ALTER TABLE cliente ALTER COLUMN rua SET NOT NULL;
                ALTER TABLE cliente ALTER COLUMN cidade SET NOT NULL;
                ALTER TABLE cliente ALTER COLUMN cep TYPE text;
                ALTER TABLE cliente ALTER COLUMN cep SET NOT NULL;
                ALTER TABLE cliente ALTER COLUMN bairro SET NOT NULL;
                ALTER TABLE cliente ALTER COLUMN estado SET NOT NULL;
                ALTER TABLE cliente ALTER COLUMN pais SET NOT NULL;
                ALTER TABLE cliente ALTER COLUMN complemento SET NOT NULL;
                """);
        }
    }
}
