// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIGO.Data;

#nullable disable

namespace SIGO.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425190852_Relatorio2")]
    partial class Relatorio2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SIGO.Objects.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("complemento");

                    b.Property<string>("Cpf_Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cpf_cnpj");

                    b.Property<DateOnly?>("DataNasc")
                        .HasColumnType("date")
                        .HasColumnName("datanasc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("estado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Obs")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("obs");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pais");

                    b.Property<string>("Razao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("razao");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rua");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("senha");

                    b.Property<int>("Sexo")
                        .HasColumnType("integer")
                        .HasColumnName("sexo");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.Property<int>("TipoCliente")
                        .HasColumnType("integer")
                        .HasColumnName("tipocliente");

                    b.HasKey("Id");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cargo");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.HasKey("Id");

                    b.ToTable("funcionario");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Funcionario_Servico", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .HasColumnType("integer")
                        .HasColumnName("idFuncionario");

                    b.Property<int>("IdServico")
                        .HasColumnType("integer")
                        .HasColumnName("idServico");

                    b.Property<string>("TempoDec")
                        .HasColumnType("text")
                        .HasColumnName("tempodec");

                    b.HasKey("IdFuncionario", "IdServico");

                    b.HasIndex("IdServico");

                    b.ToTable("funcionario_servico");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Desc")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("desc");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("TipoMarca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipomarca");

                    b.Property<int?>("VeiculoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VeiculoId");

                    b.ToTable("marca");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Oficina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cnpj");

                    b.Property<int>("Cep")
                        .HasColumnType("integer")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("complemento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Numero")
                        .HasColumnType("integer")
                        .HasColumnName("numero");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pais");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rua");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.HasKey("Id");

                    b.ToTable("oficina");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Peca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataAquisicao")
                        .HasColumnType("date")
                        .HasColumnName("dataAquisicao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Fornecedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fornecedor");

                    b.Property<DateOnly>("Garantia")
                        .HasColumnType("date")
                        .HasColumnName("garantia");

                    b.Property<int>("IdMarca")
                        .HasColumnType("integer")
                        .HasColumnName("idmarca");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo");

                    b.Property<int>("Unidade")
                        .HasColumnType("integer")
                        .HasColumnName("unidade");

                    b.Property<float>("Valor")
                        .HasColumnType("real")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("IdMarca");

                    b.ToTable("peca");
                });

            modelBuilder.Entity("SIGO.Objects.Models.PecaSubstituida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<int>("RegistroServicoId")
                        .HasColumnType("integer")
                        .HasColumnName("id_registro_servico");

                    b.HasKey("Id");

                    b.HasIndex("RegistroServicoId");

                    b.ToTable("peca_substituida");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("dataFim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("dataInicio");

                    b.Property<float>("DescontoPecaPorcentagem")
                        .HasColumnType("real")
                        .HasColumnName("descontoPecaPorcentagem");

                    b.Property<float>("DescontoPorcentagem")
                        .HasColumnType("real")
                        .HasColumnName("descontoPorcentagem");

                    b.Property<float>("DescontoReais")
                        .HasColumnType("real")
                        .HasColumnName("descontoReais");

                    b.Property<float>("DescontoServicoPorcentagem")
                        .HasColumnType("real")
                        .HasColumnName("descontoServicoPorcentagem");

                    b.Property<float>("DescontoServicoReais")
                        .HasColumnType("real")
                        .HasColumnName("descontoServicoReais");

                    b.Property<float>("DescontoTotalReais")
                        .HasColumnType("real")
                        .HasColumnName("descontoTotalReais");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observacao");

                    b.Property<float>("ValorTotal")
                        .HasColumnType("real")
                        .HasColumnName("valorTotal");

                    b.Property<float>("descontoPecaReais")
                        .HasColumnType("real")
                        .HasColumnName("descontoPecaReais");

                    b.Property<int>("idCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int>("idFuncionario")
                        .HasColumnType("integer")
                        .HasColumnName("id_funcionario");

                    b.Property<int>("idOficina")
                        .HasColumnType("integer")
                        .HasColumnName("id_oficina");

                    b.Property<int>("idVeiculo")
                        .HasColumnType("integer")
                        .HasColumnName("id_veiculo");

                    b.HasKey("Id");

                    b.HasIndex("idCliente");

                    b.HasIndex("idFuncionario");

                    b.HasIndex("idOficina");

                    b.HasIndex("idVeiculo");

                    b.ToTable("pedido");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Pedido_Peca", b =>
                {
                    b.Property<int>("IdPedido")
                        .HasColumnType("integer")
                        .HasColumnName("idpedido");

                    b.Property<int>("IdPeca")
                        .HasColumnType("integer")
                        .HasColumnName("idpeca");

                    b.Property<DateOnly>("DataInstalacao")
                        .HasColumnType("date")
                        .HasColumnName("datainstalacao");

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Observacao")
                        .HasColumnType("text")
                        .HasColumnName("observacao");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.HasKey("IdPedido", "IdPeca");

                    b.HasIndex("IdPeca");

                    b.ToTable("pedido_peca");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Pedido_Servico", b =>
                {
                    b.Property<int>("IdPedido")
                        .HasColumnType("integer")
                        .HasColumnName("idPedido");

                    b.Property<int>("IdServico")
                        .HasColumnType("integer")
                        .HasColumnName("idServico");

                    b.Property<int>("QuantVezes")
                        .HasColumnType("integer")
                        .HasColumnName("quantVezes");

                    b.HasKey("IdPedido", "IdServico");

                    b.HasIndex("IdServico");

                    b.ToTable("pedido_servico");
                });

            modelBuilder.Entity("SIGO.Objects.Models.RegistroServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataServico")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_servico");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("integer")
                        .HasColumnName("quilometragem");

                    b.Property<string>("Responsavel")
                        .HasColumnType("text")
                        .HasColumnName("responsavel");

                    b.Property<int?>("ServicoId")
                        .HasColumnType("integer")
                        .HasColumnName("id_servico");

                    b.Property<int>("VeiculoId")
                        .HasColumnType("integer")
                        .HasColumnName("id_veiculo");

                    b.HasKey("Id");

                    b.HasIndex("ServicoId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("registro_servico");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<DateOnly>("Garantia")
                        .HasColumnType("date")
                        .HasColumnName("garantia");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<double>("Valor")
                        .HasColumnType("double precision")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.ToTable("servico");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("clienteid");

                    b.Property<int>("DDD")
                        .HasMaxLength(3)
                        .HasColumnType("integer")
                        .HasColumnName("ddd");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("numero");

                    b.Property<int?>("OficinaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("OficinaId");

                    b.ToTable("telefone");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoFab")
                        .HasColumnType("integer")
                        .HasColumnName("ano");

                    b.Property<string>("ChassiVeiculo")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("chassi");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Combustivel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("combustivel");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cor");

                    b.Property<string>("NomeVeiculo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("PlacaVeiculo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("placa");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("integer")
                        .HasColumnName("quilometragem");

                    b.Property<string>("Seguro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("seguro");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TipoVeiculo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("veiculo");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Funcionario_Servico", b =>
                {
                    b.HasOne("SIGO.Objects.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("IdFuncionario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGO.Objects.Models.Servico", "Servico")
                        .WithMany("Funcionario_Servicos")
                        .HasForeignKey("IdServico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Marca", b =>
                {
                    b.HasOne("SIGO.Objects.Models.Veiculo", null)
                        .WithMany("Marcas")
                        .HasForeignKey("VeiculoId");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Peca", b =>
                {
                    b.HasOne("SIGO.Objects.Models.Marca", "Marca")
                        .WithMany("Pecas")
                        .HasForeignKey("IdMarca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("SIGO.Objects.Models.PecaSubstituida", b =>
                {
                    b.HasOne("SIGO.Objects.Models.RegistroServico", "RegistroServico")
                        .WithMany("PecasSubstituidas")
                        .HasForeignKey("RegistroServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroServico");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Pedido", b =>
                {
                    b.HasOne("SIGO.Objects.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("idCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGO.Objects.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("idFuncionario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGO.Objects.Models.Oficina", "Oficina")
                        .WithMany()
                        .HasForeignKey("idOficina")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGO.Objects.Models.Veiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("idVeiculo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");

                    b.Navigation("Oficina");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Pedido_Peca", b =>
                {
                    b.HasOne("SIGO.Objects.Models.Peca", "Peca")
                        .WithMany()
                        .HasForeignKey("IdPeca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGO.Objects.Models.Pedido", "Pedido")
                        .WithMany("Pedido_Pecas")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Peca");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Pedido_Servico", b =>
                {
                    b.HasOne("SIGO.Objects.Models.Pedido", "Pedido")
                        .WithMany("Pedido_Servicos")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGO.Objects.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("IdServico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Servico");
                });

            modelBuilder.Entity("SIGO.Objects.Models.RegistroServico", b =>
                {
                    b.HasOne("SIGO.Objects.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SIGO.Objects.Models.Veiculo", "Veiculo")
                        .WithMany("RegistroServicos")
                        .HasForeignKey("VeiculoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servico");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Telefone", b =>
                {
                    b.HasOne("SIGO.Objects.Models.Cliente", "Clientes")
                        .WithMany("Telefones")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIGO.Objects.Models.Funcionario", null)
                        .WithMany("Telefones")
                        .HasForeignKey("FuncionarioId");

                    b.HasOne("SIGO.Objects.Models.Oficina", null)
                        .WithMany("Telefones")
                        .HasForeignKey("OficinaId");

                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Veiculo", b =>
                {
                    b.HasOne("SIGO.Objects.Models.Cliente", "Cliente")
                        .WithMany("Veiculos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Cliente", b =>
                {
                    b.Navigation("Telefones");

                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Funcionario", b =>
                {
                    b.Navigation("Telefones");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Marca", b =>
                {
                    b.Navigation("Pecas");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Oficina", b =>
                {
                    b.Navigation("Telefones");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Pedido", b =>
                {
                    b.Navigation("Pedido_Pecas");

                    b.Navigation("Pedido_Servicos");
                });

            modelBuilder.Entity("SIGO.Objects.Models.RegistroServico", b =>
                {
                    b.Navigation("PecasSubstituidas");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Servico", b =>
                {
                    b.Navigation("Funcionario_Servicos");
                });

            modelBuilder.Entity("SIGO.Objects.Models.Veiculo", b =>
                {
                    b.Navigation("Marcas");

                    b.Navigation("RegistroServicos");
                });
#pragma warning restore 612, 618
        }
    }
}
